/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNILIB */

#ifndef _Included_JNILIB
#define _Included_JNILIB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNILIB
 * Method:    pm_create
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_JNILIB_pm_1create
  (JNIEnv *, jobject, jint);

/*
 * Class:     JNILIB
 * Method:    pm_destroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_JNILIB_pm_1destroy
  (JNIEnv *, jobject);

/*
 * Class:     JNILIB
 * Method:    pm_hasValue
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_JNILIB_pm_1hasValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     JNILIB
 * Method:    pm_getValue
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNILIB_pm_1getValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     JNILIB
 * Method:    getIndex
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_JNILIB_getIndex
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     JNILIB
 * Method:    pm_manage
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_JNILIB_pm_1manage
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     JNILIB
 * Method:    pm_parseFrom
 * Signature: (Ljava/lang/String;C)I
 */
JNIEXPORT jint JNICALL Java_JNILIB_pm_1parseFrom
  (JNIEnv *, jobject, jstring, jchar);

#ifdef __cplusplus
}
#endif
#endif
